############# 選單設置 ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Posts"
url = "/blog"
weight = 3

[[main]]
name = "Categories"
url = "/categories"
weight = 4


# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1
