############# 選單設置 ##############

# main menu
[[main]]
name = "首頁"
url = "/"
weight = 1

[[main]]
name = "關於"
url = "/about"
weight = 2

[[main]]
name = "文章"
url = "/posts"
weight = 3

[[main]]
name = "文章分類"
url = "/categories"
weight = 4


# footer menu
# [[footer]]
# name = "About"
# url = "/about"
# weight = 1
